# Generated by Django 4.1.7 on 2023-06-06 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_posts_owner_alter_likes_post_id_alter_likes_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.posts', verbose_name='Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
    ]
