# Generated by Django 4.1.7 on 2023-06-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_pricehistory_alter_likes_post_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
