# Generated by Django 4.1.7 on 2023-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_posts_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='access',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
