# Generated by Django 4.1.7 on 2023-06-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_likes_post_id_alter_likes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.posts', verbose_name='Posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.users', verbose_name='Users'),
        ),
    ]
