# Generated by Django 4.1.7 on 2023-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_likes_post_id_alter_likes_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='count',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
