# Generated by Django 4.1.7 on 2023-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
